title = "this is the configuration file of the Keithley plugin"

[Keithley]

[Keithley.2700]
title = "Configuration entry for a Keithley 2700 Multimeter/Switch System"

[Keithley.2700.INSTRUMENT01]
title = "Instrument in wich is plugged the switching module used for data acquisition"
rsrc_name_example_RS232 = "ASRL1::INSTR"
rsrc_name = ""
model_name = "2700"
panel = "rear"
termination_character = "Keithley must be set to LF"

[Keithley.2700.INSTRUMENT01.MODULE01]
module_name = "NONE"

[Keithley.2700.INSTRUMENT01.MODULE02]
module_name = "NONE"

[Keithley.2700.INSTRUMENT01.MODULE01.CHANNELS]

[Keithley.2700.INSTRUMENT01.MODULE02.CHANNELS]

[Keithley.2700.INSTRUMENT01.MODULE01.CHANNELS.101]

[Keithley.2701]
title = "Configuration entry for a Keithley 2701 Multimeter/Switch System"

[Keithley.2701.INSTRUMENT01]
title = "Instrument in wich is plugged the switching module used for data acquisition"
rsrc_name_example_RS232 = "ASRL1::INSTR"
rsrc_name_example_TCPIP = "TCPIP::192.168.01.01::1394::SOCKET"
rsrc_name = ""
model_name = "2701"
panel = "rear"
termination_character = "Keithley must be set to LF"

[Keithley.2701.INSTRUMENT01.MODULE01]
module_name = "NONE"

[Keithley.2701.INSTRUMENT01.MODULE02]
module_name = "NONE"

[Keithley.2701.INSTRUMENT01.MODULE01.CHANNELS]

[Keithley.2701.INSTRUMENT01.MODULE02.CHANNELS]

[Keithley.2701.INSTRUMENT01.MODULE01.CHANNELS.101]

[Keithley.2750]
title = "Configuration entry for a Keithley 2701 Multimeter/Switch System"

[Keithley.2750.INSTRUMENT01]
title = "Instrument in wich is plugged the switching module used for data acquisition"
rsrc_name_example_RS232 = "ASRL1::INSTR"
rsrc_name_example_TCPIP = "TCPIP::192.168.01.01::1394::SOCKET"
rsrc_name = ""
model_name = "2750"
panel = "rear"
termination_character = "Keithley must be set to LF"

[Keithley.2750.INSTRUMENT01.MODULE01]
module_name = "NONE"

[Keithley.2750.INSTRUMENT01.MODULE02]
module_name = "NONE"

[Keithley.2750.INSTRUMENT01.MODULE01.CHANNELS]

[Keithley.2750.INSTRUMENT01.MODULE02.CHANNELS]

[Keithley.2750.INSTRUMENT01.MODULE01.CHANNELS.101]